<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38237" started-at="2020-04-13T19:57:10Z" finished-at="2020-04-13T19:57:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="38237" started-at="2020-04-13T19:57:10Z" finished-at="2020-04-13T19:57:49Z">
      <class name="testcases.FacebookLoginTestPass">
        <test-method status="PASS" signature="initialize()[pri:0, instance:testcases.FacebookLoginTestPass@4157f54e]" name="initialize" is-config="true" duration-ms="10460" started-at="2020-04-13T19:57:30Z" finished-at="2020-04-13T19:57:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="init()[pri:0, instance:testcases.FacebookLoginTestPass@4157f54e]" name="init" duration-ms="7824" started-at="2020-04-13T19:57:41Z" finished-at="2020-04-13T19:57:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="TeardownTest()[pri:0, instance:testcases.FacebookLoginTestPass@4157f54e]" name="TeardownTest" is-config="true" duration-ms="237" started-at="2020-04-13T19:57:48Z" finished-at="2020-04-13T19:57:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TeardownTest -->
      </class> <!-- testcases.FacebookLoginTestPass -->
      <class name="testcases.FacebookLoginTestFail">
        <test-method status="PASS" signature="initialize()[pri:0, instance:testcases.FacebookLoginTestFail@327471b5]" name="initialize" is-config="true" duration-ms="10862" started-at="2020-04-13T19:57:10Z" finished-at="2020-04-13T19:57:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="init()[pri:0, instance:testcases.FacebookLoginTestFail@327471b5]" name="init" duration-ms="8711" started-at="2020-04-13T19:57:21Z" finished-at="2020-04-13T19:57:30Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Contact number error!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Contact number error!!!
at pages.FacebookLoginPage.assertLoginPageErrorMsg(FacebookLoginPage.java:139)
at testcases.FacebookLoginTestFail.init(FacebookLoginTestFail.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="TeardownTest()[pri:0, instance:testcases.FacebookLoginTestFail@327471b5]" name="TeardownTest" is-config="true" duration-ms="91" started-at="2020-04-13T19:57:30Z" finished-at="2020-04-13T19:57:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TeardownTest -->
      </class> <!-- testcases.FacebookLoginTestFail -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
