<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="37319" started-at="2020-04-12T21:47:40Z" finished-at="2020-04-12T21:48:17Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="37319" started-at="2020-04-12T21:47:40Z" finished-at="2020-04-12T21:48:17Z">
      <class name="testcases.FacebookLoginTestPass">
        <test-method status="PASS" signature="initialize()[pri:0, instance:testcases.FacebookLoginTestPass@47f37ef1]" name="initialize" is-config="true" duration-ms="9458" started-at="2020-04-13T03:17:59Z" finished-at="2020-04-13T03:18:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="init()[pri:0, instance:testcases.FacebookLoginTestPass@47f37ef1]" name="init" duration-ms="8273" started-at="2020-04-13T03:18:09Z" finished-at="2020-04-13T03:18:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="TeardownTest()[pri:0, instance:testcases.FacebookLoginTestPass@47f37ef1]" name="TeardownTest" is-config="true" duration-ms="135" started-at="2020-04-13T03:18:17Z" finished-at="2020-04-13T03:18:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TeardownTest -->
      </class> <!-- testcases.FacebookLoginTestPass -->
      <class name="testcases.FacebookLoginTestFail">
        <test-method status="PASS" signature="initialize()[pri:0, instance:testcases.FacebookLoginTestFail@3c5a99da]" name="initialize" is-config="true" duration-ms="10676" started-at="2020-04-13T03:17:40Z" finished-at="2020-04-13T03:17:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="init()[pri:0, instance:testcases.FacebookLoginTestFail@3c5a99da]" name="init" duration-ms="8633" started-at="2020-04-13T03:17:50Z" finished-at="2020-04-13T03:17:59Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Contact number error!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Contact number error!!!
	at pages.FacebookLoginPage.assertLoginPageErrorMsg(FacebookLoginPage.java:139)
	at testcases.FacebookLoginTestFail.init(FacebookLoginTestFail.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="TeardownTest()[pri:0, instance:testcases.FacebookLoginTestFail@3c5a99da]" name="TeardownTest" is-config="true" duration-ms="119" started-at="2020-04-13T03:17:59Z" finished-at="2020-04-13T03:17:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TeardownTest -->
      </class> <!-- testcases.FacebookLoginTestFail -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
